<?php

namespace Database\Seeders;

use App\Models\DetectionRule;
use Illuminate\Database\Seeder;

class DetectionRuleSeeder extends Seeder
{
    public function run(): void
    {
        $rules = [
            ['rule_id' => 'RL-SSH001', 'name' => 'Multiple failed SSH logins', 'description' => '5+ authentication failures from same source within 5 minutes.', 'severity' => 'high', 'event_type' => 'authentication_failure', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'event_type', 'op' => 'equals', 'value' => 'authentication_failure']]], 'threshold' => 5, 'time_window_minutes' => 5, 'group_by' => 'source_ip', 'mitre_technique_id' => 'T1110', 'mitre_tactic' => 'credential-access', 'tags' => ['bruteforce', 'ssh'], 'priority' => 90],
            ['rule_id' => 'RL-SSH002', 'name' => 'Successful login after repeated failures', 'description' => 'Sequence: authentication failure(s) from a source followed by authentication success from the same source within 15 minutes.', 'severity' => 'critical', 'event_type' => 'authentication_success', 'rule_type' => 'correlation', 'conditions' => ['logic' => 'SEQUENCE', 'within_minutes' => 15, 'group_by' => 'source_ip', 'steps' => [['field' => 'event_type', 'op' => 'equals', 'value' => 'authentication_failure'], ['field' => 'event_type', 'op' => 'equals', 'value' => 'authentication_success']]], 'threshold' => 1, 'time_window_minutes' => 15, 'group_by' => 'source_ip', 'mitre_technique_id' => 'T1078', 'mitre_tactic' => 'defense-evasion', 'tags' => ['bruteforce', 'compromise'], 'priority' => 95],
            ['rule_id' => 'RL-PRIV01', 'name' => 'Privileged account login anomaly', 'description' => 'Login with admin/root/administrator accounts.', 'severity' => 'medium', 'event_type' => 'authentication_success', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'event_type', 'op' => 'equals', 'value' => 'authentication_success'], ['field' => 'username', 'op' => 'in', 'value' => ['root', 'administrator', 'admin']]]], 'threshold' => 1, 'time_window_minutes' => 5, 'mitre_technique_id' => 'T1078', 'mitre_tactic' => 'defense-evasion', 'tags' => ['privileged'], 'priority' => 70],
            ['rule_id' => 'RL-PS001', 'name' => 'Suspicious PowerShell execution', 'description' => 'PowerShell with suspicious flags or script-block patterns.', 'severity' => 'high', 'event_type' => 'powershell_script', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'OR', 'items' => [['field' => 'event_type', 'op' => 'equals', 'value' => 'powershell_script'], ['field' => 'command_line', 'op' => 'contains', 'value' => 'powershell']]], 'threshold' => 1, 'time_window_minutes' => 5, 'mitre_technique_id' => 'T1059.001', 'mitre_tactic' => 'execution', 'tags' => ['powershell'], 'priority' => 85],
            ['rule_id' => 'RL-PS002', 'name' => 'Encoded PowerShell command', 'description' => 'PowerShell -EncodedCommand / FromBase64String usage.', 'severity' => 'critical', 'event_type' => 'powershell_script', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'command_line', 'op' => 'powershell_encoded', 'value' => true]]], 'threshold' => 1, 'time_window_minutes' => 5, 'mitre_technique_id' => 'T1059.001', 'mitre_tactic' => 'execution', 'tags' => ['powershell', 'encoded', 'obfuscation'], 'priority' => 95],
            ['rule_id' => 'RL-ACCT01', 'name' => 'New Windows administrator account', 'description' => 'Account creation events (4720) or net user /add.', 'severity' => 'high', 'event_type' => 'account_created', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'OR', 'items' => [['field' => 'event_type', 'op' => 'equals', 'value' => 'account_created'], ['field' => 'command_line', 'op' => 'contains', 'value' => 'net user']]], 'threshold' => 1, 'time_window_minutes' => 10, 'mitre_technique_id' => 'T1136', 'mitre_tactic' => 'persistence', 'tags' => ['persistence'], 'priority' => 85],
            ['rule_id' => 'RL-PROC01', 'name' => 'Suspicious process creation', 'description' => 'Common LOLBins / suspicious binaries spawning.', 'severity' => 'high', 'event_type' => 'process_creation', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'event_type', 'op' => 'equals', 'value' => 'process_creation'], ['field' => 'process_name', 'op' => 'regex', 'value' => '/mimikatz|psexec|wmic|certutil|bitsadmin|mshta|rundll32/i']]], 'threshold' => 1, 'time_window_minutes' => 5, 'mitre_technique_id' => 'T1059', 'mitre_tactic' => 'execution', 'tags' => ['lolbin'], 'priority' => 85],
            ['rule_id' => 'RL-AUTH01', 'name' => 'Authentication brute-force threshold', 'description' => '10+ auth failures (any service) within 5 minutes grouped by source IP.', 'severity' => 'high', 'event_type' => 'authentication_failure', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'event_type', 'op' => 'equals', 'value' => 'authentication_failure']]], 'threshold' => 10, 'time_window_minutes' => 5, 'group_by' => 'source_ip', 'mitre_technique_id' => 'T1110', 'mitre_tactic' => 'credential-access', 'tags' => ['bruteforce'], 'priority' => 80],
            ['rule_id' => 'RL-CMD01', 'name' => 'Suspicious command-line execution', 'description' => 'curl/wget + shell pipe, whoami chains, credential tools.', 'severity' => 'medium', 'event_type' => 'process_creation', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'command_line', 'op' => 'regex', 'value' => '/curl.*\|.*sh|wget.*\|.*sh|whoami|sekurlsa|lsass/i']]], 'threshold' => 1, 'time_window_minutes' => 5, 'mitre_technique_id' => 'T1059', 'mitre_tactic' => 'execution', 'tags' => ['cmdline'], 'priority' => 75],
            ['rule_id' => 'RL-IOC01', 'name' => 'Known malicious IOC match', 'description' => 'Event indicator matches an active malicious/suspicious IOC via the ingest-time indicator join (EventIocMatcher).', 'severity' => 'critical', 'event_type' => '*', 'rule_type' => 'ioc_match', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'source_ip', 'op' => 'exists', 'value' => true]]], 'threshold' => 1, 'time_window_minutes' => 5, 'mitre_technique_id' => 'T1071', 'mitre_tactic' => 'command-and-control', 'tags' => ['ioc', 'ti'], 'priority' => 90],
            ['rule_id' => 'RL-CRED01', 'name' => 'Potential credential access behavior', 'description' => 'LSASS access, registry SAM reads, ntdsutil patterns.', 'severity' => 'high', 'event_type' => 'process_creation', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'command_line', 'op' => 'regex', 'value' => '/lsass|sam\.hiv|ntdsutil|procdump/i']]], 'threshold' => 1, 'time_window_minutes' => 5, 'mitre_technique_id' => 'T1003', 'mitre_tactic' => 'credential-access', 'tags' => ['creds'], 'priority' => 90],
            ['rule_id' => 'RL-NET01', 'name' => 'Large number of requests from one source', 'description' => '30+ events from single source IP in 5 minutes.', 'severity' => 'medium', 'event_type' => '*', 'rule_type' => 'threshold', 'conditions' => ['logic' => 'AND', 'items' => [['field' => 'source_ip', 'op' => 'exists', 'value' => true]]], 'threshold' => 30, 'time_window_minutes' => 5, 'group_by' => 'source_ip', 'mitre_technique_id' => 'T1046', 'mitre_tactic' => 'discovery', 'tags' => ['scan'], 'priority' => 60],
        ];
        foreach ($rules as $r) {
            DetectionRule::firstOrCreate(['rule_id' => $r['rule_id']], [...$r, 'cooldown_minutes' => 15, 'enabled' => true, 'status' => 'active']);
        }
    }
}
